---
title: "Lecture"
output: html_document
date: "2022-09-22"
---

### Sept 22, 2022

```{r}

library(tidyverse)
library(palmerpenguins)
penguins 

```

```{r}
penguins$year != "2008"
```

```{r}
penguins %>%
  select(bill_length_mm:body_mass_g) %>%
  as.matrix()
```

```{r}
x<- runif(n=1, min= 3, max=4)
```
print(x)

```{r}
if(x>3) {
  y<- 10
} else {
  y<- 0
}
```

```{r}
y <- if(x > 3) {
    10
  } else { 
    0
  }
y
```



```{r}
x<- rnorm(n =1, mean= 0, sd = 1)
if(x>0){
  penguins %>%
    filter(species == "Chinstrap")
} else {
  penguins %>% 
    filter(species == "Gentoo")
}
```

```{r}
## define the loop to iterate over
x <- c("a", "b", "c", "d")

## create for loop
for(i in 1:3) {
        ## Print out each element of 'x'
        print(x[i])  
}
```

```{r eval=FALSE, include=FALSE}
for (i in seq_along(penguins)) {
  x <- penguins %>% pull(i) 
  if(as.numeric(x)) {
   y <- mean(x, na.rm= TRUE)
  } else {
   y <- NA
  } 
  print(y)
}
```
```{r}
count <- 0
while(count < 10) {
        print(count)
        count <- count + 1
}
```
## \n <- new line
## cat is equivalent to print but removes new lines and just keep text


```{r}
f <- function() {
        # this is the function body
        hello <- "Hello, world!\n"
        cat(hello) 
}
f()
```

```{r}
f <- function(num) {
        for(i in seq_len(num)) {
                hello <- "Hello, world!\n"
                cat(hello) 
        }
}
f(2)
```

```{r}
f <- function(num){
        hello <- "Hello, world!\n"
        for(i in seq_len(num)) {
                 cat(hello)
        } 
        chars <- nchar(hello) * num
        chars
}
meaningoflife <- f(3)
```
